#!/bin/bash
# push all repos to origin

# get options
if [ $# -eq 0 ]; then
    main=`pwd`
elif [ $# -eq 1 ]; then
    main=$1
else
    echo 'Usage: scetter dir'
    exit
fi

# get timestamp
td=`date`
echo $td

# find all non-vim repos
for repo in `find $main -name .git | awk '!/\.vim/ { print }'`; do
    slang $repo
done
