#!/bin/bash
# push a directory

# get options
if [ $# -eq 0 ]; then
    src=`pwd`
elif [ $# -eq 1 ]; then
    src=$1
else
    echo 'Usage: sling repo'
    exit
fi

# get timestamp
td=`date`
echo $td

# commit and push from source
cd $src
git add .
git commit -a -m "$td" --allow-empty
git push origin
